multi_branch_env:
  hostname: tr.rt.gw
  user: root
  site_url: https://pranjal-wadhwani.tr.rt.gw
  main_site: pranjal-wadhwani.tr.rt.gw
  deploy_path: /opt/easyengine/sites/pranjal-wadhwani.tr.rt.gw/app/htdocs
